name: i_am_richer
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter




dev_dependencies:
  flutter_test:
    sdk: flutter




flutter:
  uses-material-design: true
  assets:
    - assets/images/dorcas.jpg

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf



fonts:
  - family: Source Sans Pro
    fonts:
      - asset: fonts/SourceSansPro-Regular.ttf

